name: Draw Pikachu

on:
  push:
    branches:
      - main

jobs:
  draw:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the script
      run: |
        python pikachu.py
        sudo apt-get install -y imagemagick
        import -window root pikachu.png || echo "Skipping screenshot as it may not be needed"
        mv pikachu.png ./docs/pikachu.png || echo "Image might not have been generated"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/pikachu.png || echo "Nothing to add"
        git commit -m "Add Pikachu image" || echo "Nothing to commit"
        git push || echo "Nothing to push"
